import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..')) 
# sys.path.append(os.path.dirname(os.path.realpath(__file__)))
question_store = {
                    "Easy":[
                        {
                            'text':'Q1',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Easy',
                            'marks':1
                        },
                        {
                            'text':'Q2',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Easy',
                            'marks':2,
                        },
                        {
                            'text':'Q5',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Easy',
                            'marks':3,
                        },
                        {
                            'text':'Q8',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Easy',
                            'marks':2,
                        }
                        ],
                    "Medium":[
                        {
                            'text':'Q3',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Medium',
                            'marks':2,
                        },
                        {
                            'text':'Q7',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Medium',
                            'marks':3,
                        },
                        {
                            'text':'Q9',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Medium',
                            'marks':5,
                        }
                    ],
                    "Hard":[
                        {
                            'text':'Q4',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Hard',
                            'marks':9,
                        },
                        {
                            'text':'Q6',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Hard',
                            'marks':7,
                        },
                        {
                            'text':'Q10',
                            'subject':'fs29',
                            'topic':'fsmilli14667',
                            'difficulty':'Hard',
                            'marks':5,
                        }
                    ]
}